-- CÓDIGO DA AULA 06 - ALTERANDO A ESTRUTURA DA TABELA

-- PARA ALTERAR O NOME DA TABELA
ALTER TABLE pessoas RENAME TO humanos;

-- PARA COLOCAR O CAMPO DEPOIS DE OUTRO CAMPO
ALTER TABLE pessoas ADD COLUMN profissao VARCHAR(10) AFTER nome;

-- PRA ALTERAR O TIPO PRIMITIFO DO CAMPO
ALTER TABLE pessoas MODIFY COLUMN profissao VARCHAR(20) NOT NULL DEFAULT '';

-- PARA ALTERAR O NOME DO CAMPO
ALTER TABLE pessoas CHANGE COLUMN profissao prof VARCHAR(20);

-- PARA COLOCAR O CAMPO EM PRIMEIRO
ALTER TABLE pessoas ADD COLUMN hobby VARCHAR(10) FIRST;

-- PARA DELETAR UM CAMPO
ALTER TABLE pessoas DROP COLUMN profissao;
DESC humanos;
SELECT * FROM humanos;


CREATE TABLE IF NOT EXISTS cursos (
	nome VARCHAR(30) NOT NULL UNIQUE, -- PARA NÃO REPETIR O NOME
    descricao TEXT,
    carga INT UNSIGNED, -- PARA ENCONOMIZAR UM BYTE POR REGISTRO
    totalAulas INT UNSIGNED,
    ano YEAR DEFAULT '2025' -- DEFINIÇÃO PADRÃO
) DEFAULT CHARSET = utf8;

ALTER TABLE cursos ADD COLUMN idcursos INT FIRST;
ALTER TABLE cursos ADD PRIMARY KEY (idcursos);

DESC cursos;
-- DROP TABLE IF EXISTS cursos;
